In [1]:
with open('day8.txt') as f:
    content = f.readlines()
content = [x.strip('\n') for x in content]

### part 1

In [26]:
import numpy as np
import re

In [100]:
def rect(x,y,screen):
    screen[:y,:x] = 1
    return screen

In [92]:
def rotate_row(x,step,screen):
    lights = np.nonzero(screen[x,:])[0]
    screen[x,:] = 0
    for light in lights:
        if light + step < screen.shape[1]:
            screen[x,light+step]=1
        else:
            screen[x,light+step-screen.shape[1]]=1
    return screen

In [93]:
def rotate_col(y,step,screen):
    lights = np.nonzero(screen[:,y])[0]
    screen[:,y]=0
    for light in lights:
        if light + step < screen.shape[0]:
            screen[light+step,y]=1
        else:
            screen[light+step-screen.shape[0],y]=1
    return screen

In [110]:
screen = np.zeros((6,50))
for con in content:
    x = int(re.findall("\d+", con)[0])
    y = int(re.findall("\d+", con)[1])
    if 'rect' in con:
        screen = rect(x,y,screen)
    if 'column' in con:
        screen = rotate_col(x,y,screen)
    if 'row' in con:
        screen = rotate_row(x,y,screen)        

In [112]:
np.sum(screen)

119.0

### part 2

In [129]:
for x in range(0,50,5):
    print (screen[:,x:x+5])
    print ()

[[ 1.  1.  1.  1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  0.]]

[[ 1.  1.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]

[[ 1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 1.  1.  1.  1.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.]]

[[ 1.  1.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]

[[ 0.  1.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 1.  1.  1.  0.  0.]]

[[ 1.  1.  1.  1.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]

[[ 0.  1.  1.  0.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 0.  1.  1.  0.  0.]]

[[ 0.  1.  1.  0.  0